### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by djindjic** [crabhi/bug-killing-spree#1]
why don't you have issues [here](https://github.com/crabhi/karma-ubuntu-reporter)? :smile:

**Comment by crabhi** [comment]
Huh? These projects are completely unrelated. I don't plan to work actively on karma-ubuntu-reporter apart from accepting some simple pull requests. Feel free to create one or just fork and use your fork.

**Comment by djindjic** [comment]
this is only one contact to I found :D
ok thanks, btw it works for me now! You have my star!

**Comment by crabhi** [comment]
Anyway, the issues are here, since now: https://github.com/crabhi/karma-ubuntu-reporter/issues

Cheers.
